### ISSUE TITLE
Increase space after "Text or image to encrypt and expire"

### ISSUE THREAD

**Issue by sg-4xxi** [caesar-team/caesar.team#6]
Increase space after "Text or image to encrypt and expire"
<img width="827" alt="Снимок экрана 2020-04-09 в 18 52 45" src="https://user-images.githubusercontent.com/26769057/78914692-73cfc980-7a93-11ea-9fa1-04360229b4fd.png">

**Comment by okomarova** [comment]
as you can see we increased those spaces 
![image](https://user-images.githubusercontent.com/57711498/84158234-522f9600-aa74-11ea-9e2c-2ba7791d16e8.png)
