### ISSUE TITLE
Textarea with link and password are not selectable

### ISSUE THREAD

**Issue by mazanax** [caesar-team/caesar.team#8]
After creating of a secret message you cannot select something in the textarea with link and password.

You can only select whole text by `CMD (CTRL) + A`.
Firefox: 74.0.1

https://youtu.be/cYqZhuPw-4A

**Comment by beshkenadze** [comment]
@mazanax thx, but it's can be selected due to realization (thanks to css & html), but we are missing the copy password button,

**Comment by beshkenadze** [comment]
Fixed.
